<?php
/**
 * Pagar.me develop exam
 *
 * @author Joubert RedRat <me+github@redrat.com.br>
 * @copyright 2017, Pagar.me
 * @link https://pagar.me
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Manufacturer;
use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package AppBundle\Repository
 */
class ManufacturerRepository extends EntityRepository
{
    /**
     * Add Manufacturer to database
     *
     * @param Manufacturer $manufacturer
     * @return void
     */
    public function add(Manufacturer $manufacturer): void
    {
        $em = $this->getEntityManager();
        $em->persist($manufacturer);
        $em->flush();
    }

    /**
     * Update Manufacturer on database
     *
     * @param Manufacturer $manufacturer
     * @return Manufacturer
     */
    public function update(Manufacturer $manufacturer): Manufacturer
    {
        $em = $this->getEntityManager();
        $em->persist($manufacturer);
        $em->flush($manufacturer);

        return $manufacturer;
    }

    /**
     * Delete Manufacturer on database
     *
     * @param Manufacturer $manufacturer
     * @return bool
     */
    public function delete(Manufacturer $manufacturer): bool
    {
        $em = $this->getEntityManager();
        $em->remove($manufacturer);
        $em->flush($manufacturer);

        return true;
    }
}
