<?php
/**
 * Pagar.me develop exam
 *
 * @author Joubert RedRat <me+github@redrat.com.br>
 * @copyright 2017, Pagar.me
 * @link https://pagar.me
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package AppBundle\Repository
 */
class ProductRepository extends EntityRepository
{
    /**
     * Add Product to database
     *
     * @param Product $product
     * @return void
     */
    public function add(Product $product): void
    {
        $em = $this->getEntityManager();
        $em->persist($product);
        $em->flush();
    }

    /**
     * Update Product on database
     *
     * @param Product $product
     * @return Product
     */
    public function update(Product $product): Product
    {
        $em = $this->getEntityManager();
        $em->persist($product);
        $em->flush($product);

        return $product;
    }

    /**
     * Delete Product on database
     *
     * @param Product $product
     * @return bool
     */
    public function delete(Product $product): bool
    {
        $em = $this->getEntityManager();
        $em->remove($product);
        $em->flush($product);

        return true;
    }
}
