<?php
/**
 * Pagar.me develop exam
 *
 * @author Joubert RedRat <me+github@redrat.com.br>
 * @copyright 2017, Pagar.me
 * @link https://pagar.me
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Purchase;
use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package AppBundle\Repository
 */
class PurchaseRepository extends EntityRepository
{
    /**
     * Add Purchase to database
     *
     * @param Purchase $purchase
     * @return void
     */
    public function add(Purchase $purchase)
    {
        $em = $this->getEntityManager();
        $em->persist($purchase);
        $em->flush();
    }

    /**
     * Update Purchase on database
     *
     * @param Purchase $purchase
     * @return Purchase
     */
    public function update(Purchase $purchase): Purchase
    {
        $em = $this->getEntityManager();
        $em->persist($purchase);
        $em->flush($purchase);

        return $purchase;
    }

    /**
     * Delete Purchase on database
     *
     * @param Purchase $purchase
     * @return bool
     */
    public function delete(Purchase $purchase): bool
    {
        $em = $this->getEntityManager();
        $em->remove($purchase);
        $em->flush($purchase);

        return true;
    }
}
