admin_manufacturer_index:
    path:     /
    defaults: { _controller: "AppBundle:Manufacturer:index" }
    methods:  GET

admin_manufacturer_new:
    path:     /new
    defaults: { _controller: "AppBundle:Manufacturer:new" }
    methods:  [GET, POST]

admin_manufacturer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Manufacturer:edit" }
    methods:  [GET, POST]

admin_manufacturer_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:Manufacturer:delete" }
    methods:  [GET, DELETE]