admin_product_index:
    path:     /
    defaults: { _controller: "AppBundle:Product:index" }
    methods:  GET

admin_product_new:
    path:     /new
    defaults: { _controller: "AppBundle:Product:new" }
    methods:  [GET, POST]

admin_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Product:edit" }
    methods:  [GET, POST]

admin_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Product:delete" }
    methods:  [GET, DELETE]
