cart:
    resource: "@AppBundle/Resources/config/routing/cart.yml"
    prefix: /cart

app_admin_manufacturer:
    resource: "@AppBundle/Resources/config/routing/manufacturer.yml"
    prefix: /admin/manufacturer

app_admin_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix: /admin/product
