services:
    app.manufacturer.repository:
        class: AppBundle\Repository\ManufacturerRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Manufacturer

    app.product.repository:
        class: AppBundle\Repository\ProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Product

    app.purchase.repository:
        class: AppBundle\Repository\PurchaseRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Purchase

    app.purchase_product.repository:
        class: AppBundle\Repository\PurchaseProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\PurchaseProduct

    app.purchase.service:
        class: AppBundle\Services\PurchaseService
        arguments:
            - "@app.purchase.repository"
            - "@app.purchase_product.repository"
            - "@app.product.repository"