AppBundle\Entity\Manufacturer:
    type: entity
    table: manufacturers
    repositoryClass: AppBundle\Repository\ManufacturerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        name:
            type: string
            length: 255
    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]
        preUpdate: [ setUpdatedAt ]
    oneToMany:
        products:
            targetEntity: AppBundle\Entity\Product
            mappedBy: manufacturer