AppBundle\Entity\Manufacturer:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ManufacturerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks:
            prePersist: [ setCreatedAt ]
            preUpdate: [ setUpdatedAt ]
